### ISSUE TITLE
Cannot find module 'dist/main' after upgrading to 10.1.12

### ISSUE THREAD

**Issue by michael-land** [nestjs/nest-cli#2247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
❯ pnpm dev

> @app/scheduler@1.1.0 dev /Users/.../apps/app-scheduler
> nest start --watch

>  SWC  Running...
Successfully compiled: 3 files with swc (6.47ms)

 Error  Cannot find module 'dist/main'
Require stack:
- /Users/.../node_modules/.pnpm/@nestjs+cli@10.1.12_@swc+cli@0.1.62_@swc+core@1.3.78/node_modules/@nestjs/cli/actions/start.action.js
- /Users/.../node_modules/.pnpm/@nestjs+cli@10.1.12_@swc+cli@0.1.62_@swc+core@1.3.78/node_modules/@nestjs/cli/actions/index.js
- /Users/.../node_modules/.pnpm/@nestjs+cli@10.1.12_@swc+cli@0.1.62_@swc+core@1.3.78/node_modules/@nestjs/cli/commands/command.loader.js
- /Users/.../node_modules/.pnpm/@nestjs+cli@10.1.12_@swc+cli@0.1.62_@swc+core@1.3.78/node_modules/@nestjs/cli/commands/index.js
- /Users/.../node_modules/.pnpm/@nestjs+cli@10.1.12_@swc+cli@0.1.62_@swc+core@1.3.78/node_modules/@nestjs/cli/bin/nest.js

Watching for file changes.
```

### Expected behavior

no error

### Package version

10.1.12

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by michael-land** [comment]
should be related to #2245

**Comment by michael-land** [comment]
The problem persists even after upgrading to version 10.1.13. The problem revolves around the inability of the nodejs require.resolve function to function correctly with absolute paths. This issue can be observed in the code snippet available at this GitHub link: https://github.com/nestjs/nest-cli/blob/master/lib/configuration/defaults.ts#L29C14-L29C27. By default, the "outdir" is set to "dist" but I recommend changing it to "./dist"

To address this problem, a workaround involves adding the following line to your tsconfig.json file to override the default value:
{
    "outDir": "./dist",
}
```

**Comment by michael-land** [comment]
The problem persists even after upgrading to version 10.1.13. in this pr #2228, it resolve absolute path.  The problem revolves around the inability of the nodejs require.resolve function to function correctly with absolute paths. 

https://github.com/nestjs/nest-cli/blob/master/lib/configuration/defaults.ts#L29C14-L29C27.

By default, the "outdir" is set to "dist" but I recommend changing it to "./dist" 

To address this problem, a workaround involves adding the following line to your tsconfig.json file to override the default value:
```
{
    "outDir": "./dist",
}
```


to reproduce, see 
https://codesandbox.io/p/sandbox/github/nestjs/typescript-starter/tree/master?file=%2Fpackage.json%3A29%2C26


<img width="1728" alt="CleanShot 2023-08-22 at 22 03 20@2x" src="https://github.com/nestjs/nest-cli/assets/33362998/706ce009-ed88-45ce-b8eb-0ae7bc6e1b29">

**Comment by kamilmysliwiec** [comment]
Should we revert https://github.com/nestjs/nest-cli/pull/2228 for the time being then?

**Comment by zhangyuang** [comment]
The problem remains

**Comment by kamilmysliwiec** [comment]
Could you test with 10.1.14?

**Comment by michael-land** [comment]
> Could you test with 10.1.14?

10.1.14 is functional as expected
